name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      #- name: Install dependencies
      #  run: go mod tidy

      - name: Build
        run: GOARCH=${{ matrix.arch }} make geth.

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geth-binary-${{ matrix.arch }}
          path: ./build/bin/geth

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/bin/geth
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}-(${{ matrix.arch }})"
          draft: false
          prerelease: false
